# Uncomment this line to define a global platform for your project
platform :ios, '9.3'
# Uncomment this line if you're using Swift
use_frameworks!

target 'My Water' do
   pod 'JBChartView', '~> 3.0.12'
   pod 'OGCSensorThings', '~> 2.1.5'
   pod 'AeroGearOAuth2', '~> 0.5.1'
   pod 'Alamofire', '~> 3.5.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
