# Uncomment this line to define a global platform for your project
platform :ios, '9.3'
# Uncomment this line if you're using Swift
use_frameworks!

target 'My Water' do
   pod 'JBChartView'
   pod 'OGCSensorThings'
end

target 'WatermeterofTheFutureTests' do

end

target 'WatermeterofTheFutureUITests' do

end

