//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class PAP: APIBase {
    /**

     - parameter subjectId: (path) id of the policy 
     - parameter bodyContent: (body) Size of array 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func papV1SubjectSubjectIdPost(subjectId subjectId: String, bodyContent: String, completion: ((error: ErrorType?) -> Void)) {
        papV1SubjectSubjectIdPostWithRequestBuilder(subjectId: subjectId, bodyContent: bodyContent).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     - POST /pap/v1/subject/{subjectId}
     - Posts a new policy object 
     
     - parameter subjectId: (path) id of the policy 
     - parameter bodyContent: (body) Size of array 

     - returns: RequestBuilder<Void> 
     */
    public class func papV1SubjectSubjectIdPostWithRequestBuilder(subjectId subjectId: String, bodyContent: String) -> RequestBuilder<Void> {
        var path = "/pap/v1/subject/{subjectId}"
        path = path.stringByReplacingOccurrencesOfString("{subjectId}", withString: "\(subjectId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = bodyContent.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
